#Input Data
dataIPM=read.csv('C:/Users/Asus/Downloads/cobaipm.csv')
df<-dataIPM[,2:5]
kabkot=dataIPM[,1]
row.names(df)=kabkot

#Korelasi Plot
library (corrplot)
library (RColorBrewer)
M<-cor(df)
corrplot(M,type="upper",order="hclust",col=brewer.pal(n=8,name="RdYlBu"))

#Standardisasi
df<-scale (df)

#Heatmap Euclidean Komponen IPM
library(factoextra)
distance<-get_dist(df)
fviz_dist(distance,gradient=list(low="white",mid="red", high="dark blue"))

#Silhouette method
# Compute and plot wss for k = 2 to k = 15
k.values <- 2:15

library(purrr)
library(cluster)

# kmeans
avg_sil_kmeans <- function(k) {
  km.res <- kmeans(df, centers = k, nstart = 25)
  ss <- silhouette(km.res$cluster, dist(df))
  mean(ss[, 3])  }
sil_kmeans <- map_dbl(k.values, avg_sil_kmeans)

# Hkmeans
avg_sil_hkmeans <- function(k) {
  km.res <- hkmeans(df, k = k)
  ss <- silhouette(km.res$cluster, dist(df))
  mean(ss[, 3])  }
sil_hkmeans <- map_dbl(k.values, avg_sil_hkmeans)

# kmedoids pam
avg_sil_kmedoids <- function(k) {
  km.res <- pam(df, k = k)
  ss <- silhouette(km.res$clustering, dist(df))
  mean(ss[, 3])  }
sil_kmedoids <- map_dbl(k.values, avg_sil_kmedoids)

# CLARA
avg_sil_clara <- function(k) {
  km.res <- clara(df, k = k)
  ss <- silhouette(km.res$clustering, dist(df))
  mean(ss[, 3])  }
sil_clara <- map_dbl(k.values, avg_sil_clara)

# Hclust
avg_sil_hclust <- function(k) {
  km.res <- hclust(distance)
  grp <- cutree(km.res, k = k)
  ss <- silhouette(grp, dist(df))
  mean(ss[, 3])  }
sil_hclust <- map_dbl(k.values, avg_sil_hclust)

# fuzzy
angka=c(2,3,4,6,7,8,10,11)
sil_fuzzy=data.frame()
for (i in angka) {
  km.res <- fanny(df,k = i)
  ss <- silhouette(km.res$clustering, dist(df))
  sil_fuzzy[i,1]=mean(ss[, 3])
}

# plot silhouette
plot(k.values, sil_kmedoids , type = "b", pch = 19, frame = FALSE, xlab = "Number of clusters K", ylab = "Average Silhouettes")
lines(k.values,sil_hkmeans,col='red', type = "b",pch = 19)
lines(k.values,sil_clara,col='blue', type = "b",pch = 19)
lines(k.values,sil_kmeans,col='brown', type = "b",pch = 19)
lines(k.values,sil_hclust,col='green', type = "b",pch = 19)

#Tabel Silhouette
silhuet=data.frame(klaster=k.values,Kmeans=sil_kmeans,HKmeans=sil_hkmeans, KMedoids=sil_kmedoids,CLARA=sil_clara,HClust=sil_hclust)
silhuet
sil_fuzzy

# Clustering with KMeans
IPMCluster <- kmeans(dataIPM[,3:6], center=3, nstart=20)
tabel<-cbind(IPMCluster$cluster, dataIPM$provinsi)
tabel<-data.frame(tabel)

